name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"        # every day at midnight UTC
  workflow_dispatch:            # manual trigger

permissions:
  contents: write               # needed to push to main branch

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake SVG only
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            outputs/github-contribution-grid-snake.svg
            outputs/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add outputs/
          git diff --staged --quiet || git commit -m "Update GitHub contribution snake animation"
          git push